sudo: required
language: generic

services:
    - docker

before_install: 
    - docker build -t igorkuzmin/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true igorkuzmin/react-test npm run test -- --coverage

after_success:
    - docker build -t igorkuzmin/multi-client ./client
    - docker build -t igorkuzmin/multi-nginx ./nginx
    - docker build -t igorkuzmin/multi-server ./server
    - docker build -t igorkuzmin/multi-server ./worker 
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push to Docker Hub
    - docker push igorkuzmin/multi-client
    - docker push igorkuzmin/multi-nginx
    - docker push igorkuzmin/multi-server
    - docker push igorkuzmin/multi-worker